separador=("-_-"*30)

print("1-.presupuesto de ventas")
print(separador)
print("*primer semestre*")
primer=(int(input("cuanto fue su primer semetre: ")))
total_semestre=(primer)
print("total de primer semestre: ",total_semestre)
print("*segundo semestre*")
primer1=(int(input("cuanto fue su segundo semetre: ")))
total_semestre1=(primer1)
print("total de segundo semestre: ",total_semestre1)
total_semestresd=(total_semestre + total_semestre1)
print("este es el total: ",total_semestresd)
print(separador)



print("2-.presupuesto de produccion")
print("*primer semestre*")
ventas_presu=(int(input("ventas presupuestadas:")))
inventario_final=(int(input("inventario final:")))
necesidad_produccion=(int(input("necesidad de produccion:")))
inventario_inicial=(int(input("inventario inicial:")))
produccion_requerida=(int(input("produccion requerida:")))
print("*segundo semestre*")
ventas_presu2=(int(input("ventas presupuestadas:")))
inventario_final2=(int(input("inventario final:")))
necesidad_produccion2=(int(input("necesidad de produccion:")))
inventario_inicial2=(int(input("inventario inicial:")))
produccion_requerida2=(int(input("produccion requerida:")))
print(separador)



print("3-.presupuesto de requisitos de materia prima")
material_necesario=(int(input("cuanto material se necesita:")))
numero_x=(int(input("cuantos:")))
total_1=(numero_x * material_necesario)
print("total:",total_1)
costo_kg=(int(input("cual es el costo de cada material:")))
total=(total_1 * costo_kg)
print("total: ",total)
print(separador)

print("4-.presupuesto de compra de materiales")
print("*primer semestre*")
requisitos=(int(input("requisitos de la produccion:")))
inventario_deseado=(int(input("inventario final deseado:")))
necesidad=(int(input("necesidad de compra:")))
inicial=(int(input("inventario inicial ")))
totalacop=(int(input("total a comprar: ")))
kg=(int(input("costos por kg:")))
costosdecompas=(int(input("costo de compras:")))
print("*segundo semestre*")
requisitos1=(int(input("requisitos de la produccion:")))
inventario_deseado1=(int(input("inventario final deseado:")))
necesidad1=(int(input("necesidad de compra:")))
inicial1=(int(input("inventario inicial ")))
totalacop1=(int(input("total a comprar: ")))
kg1=(int(input("costos por kg:")))
costosdecompas1=(int(input("costo de compras:")))
suma23=(costosdecompas + costosdecompas1)
print("total",suma23)
print(separador)




print("5-.presupuestp de mano de obra directa")
print("*primer semestre*")
requisitos_prod=(int(input("requisitos de produccion: ")))
horas_prod=(int(input("horas de produccion: ")))
total_hores=(requisitos_prod * horas_prod)
print("total de horas: ",total_hores)
costosxhora=(int(input("costos por hora:")))
total_kostes=(costosxhora * total_hores)
print("el total de costos de mano de obra: ",total_kostes)
print("*segundo semestre*")
requisitos_prod3=(int(input("requisitos de produccion: ")))
horas_prod3=(int(input("horas de produccion: ")))
total_hores3=(requisitos_prod3 * horas_prod3)
print("total de horas: ",total_hores3)
costosxhora3=(int(input("costo por hora:")))
total_kostres3=(costosxhora3 * total_hores3)
print("el total de costos de mano de obra: ",total_kostres3)
total_horines=(total_hores + total_hores3)
print(separador)




print("6-.presupuesto de gastos indirectos de fabricacion")
depreciacion=(int(input("depreciacion: ")))
supervicion=(int(input("supervison: ")))
seguro=(int(input("seguro: ")))
mantenimiento=(int(input("mantenimiento: ")))
accesorios=(int(input("accesorios: ")))
energeticos=(int(input("energeticos")))
totaluwu=(depreciacion + supervicion + seguro + mantenimiento + accesorios + energeticos)
print("total: ", totaluwu)
tasa_de=(totaluwu / total_horines)
print("tasa de aplicacion: ", tasa_de)
print(separador)




print("7-.presupuesto de gastos de administracion y ventas")
suñl=(int(input("sueldos: ")))
com=(int(input("comisiones: ")))
publoi=(int(input("publicidad: ")))
acced=(int(input("accesorios: ")))
deper=(int(input("depreciacion: ")))
varios=(int(input("varios: ")))
sumni=(suñl + com + publoi + acced + deper + varios)
print("total: ", sumni)



print(separador)
print("8-.presupuesto de inventarios finales")
uni=(int(input("costo unitario de la materia: ")))
x_cua=(int(input("cuanto ocupa: ")))
multi=(uni * x_cua)
print("total: ", multi)
print(separador)
mano=(int(input("mano de obra: ")))
x_yojua=(int(input("cuanto ocupa:" )))
multi1=(mano * x_yojua)
print("total: ",multi1)
print(separador)
gas_favib=(int(input("gastos indirectos de fabricacion: ")))
x_tut=(int(input("cuanto ocupa: ")))
multi2=(gas_favib * x_tut)
print("total: ", multi2)
sumooo=(multi + multi1 + multi2)
print("costo por producion: ", sumooo)
preciod=(int(input("precio inicial: ")))
inteli=(preciod * uni)
print("inventario final: " , inteli)
print(separador)




print("9-.presupuesto de costos de venta")
print("*primer semestre*")
mate_req=(int(input("materia prima requerida:")))
mano_obra=(int(input("mano de obra: ")))
gastos_fav=(int(input("gastos indirectos de faricacion: ")))
cost=(int(input("costos de produccion: ")))
inventa_de_term=(int(input("(+)inventario inicial de articulos terminados: ")))
disponiblre=(int(input("disponible: ")))
invent_fin_rem=(int(input("(-)inventario final de articulos terminados: ")))
print("*segundo semestre*")
wmate_req=(int(input("materia prima requerida:")))
wmano_obra=(int(input("mano de obra: ")))
wgastos_fav=(int(input("gastos indirectos de faricacion: ")))
wcost=(int(input("costos de produccion: ")))
winventa_de_term=(int(input("(+)inventario inicial de articulos terminados: ")))
wdisponiblre=(int(input("disponible: ")))
winvent_fin_rem=(int(input("(-)inventario final de articulos terminados: ")))
total_mat=(mate_req + wmate_req)
print(separador)
total_mat=(mate_req + wmate_req)
print("total de materia prima requerida", total_mat)
total_mano=(mano_obra + wmano_obra)
print("total de mano de obra: ", total_mano)
total_gas=(gastos_fav + wgastos_fav)
print("total de gastos indirectos de fabricacion: ", total_gas)
total_prod=(cost + wcost)
print("total de costos de produccion: ", total_prod)
total_invent_i=(inventa_de_term + winventa_de_term)
print("total de inventario inicial de articulos terminados: ", total_invent_i)
total_disp=(disponiblre + wdisponiblre)
print("total disponible: ", total_disp)
total_inv_t=(invent_fin_rem + winvent_fin_rem)
print("total de inventario final de articulos terminados: ", total_inv_t)
print(separador)

print("estado de resultados")
dentas=(int(input("ventas: ")))
coto=(int(input("costo de ventas: ")))
utin=(int(input("utilidad bruta: ")))
fgas=(int(input("gastos de operacion: ")))
utilidad_ope=(int(input("utilidad de operacion: ")))
print(separador)
print("resultado integral de financiamiento")
interesf=(int(input("gastos por interes: ")))
utilidad_neta=(int(input("utilidad neta: ")))
print(separador)
print("balance general presupuestado")
print(separador)
print("activo circulante:")
print(separador)


bancos=int(input("banco: "))
clientes=int(input("clientes: "))
productos_terminados=int(input("productos terminados: "))
materia_prima=int(input("materia prima: "))
total_circ=(bancos + clientes + productos_terminados + materia_prima)
print("este es el total circulante: ", total_circ)
print(separador)


print("empecemos con los activos no circulantes")
print(separador)
terreno=int(input("terrenos: "))
edificios_equiopoind=int(input("edificio y equipos industriales: "))
depreciacion_acom=int(input("depreciacion acomulada: "))
total_nocirc=(terreno - edificios_equiopoind + depreciacion_acom)
print("este es el total de no circulantes:", total_nocirc)
print(separador)
total_activ=(total_circ + total_nocirc)
print("total de activos: " , total_activ)
print(separador)


actibe=(int(input("total de activos: ")))
pasivo_corte=(int(input("pasivos a corto plazo: ")))
proveg=(int(input("proveedores: ")))
documentst=(int(input("documentos por pagar: ")))
tota_pasice=(pasivo_corte + proveg + documentst)
print("total de pasivo: ", tota_pasice)
print(separador)


capital_cont=(int(input("capital contable: ")))
capital_apa=(int(input("capital aportado: ")))
capital_ganado=(int(input("capital ganado")))
totit=(capital_cont + capital_apa + capital_ganado)
print("total capital contable: ", totit)
print(separador)


